

spring:
   jpa:
     properties:
         hibernate:
            jdbc:
                lob:
                   non_contextual_creation: true
            show_sql: true
            format_sql: true
            ddl-auto: update
              
   datasource:
        url: jdbc:postgresql://localhost:5432/Portfolio
        username: postgres
        password: admin       

